"""added minutes field

Revision ID: e9e2bbe4cb83
Revises: 6bf4aa57c865
Create Date: 2024-12-15 18:23:12.423195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e2bbe4cb83'
down_revision = '6bf4aa57c865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Float(), nullable=True))

    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Float(), nullable=True))

    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.drop_column('minutes')

    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.drop_column('minutes')

    with op.batch_alter_table('master_table', schema=None) as batch_op:
        batch_op.drop_column('minutes')

    # ### end Alembic commands ###
